name: "CD Pipeline"

on:
  workflow_run:
    workflows: ["sample react workflow"]
    types:
      - completed

jobs:  
  deploy:    
      runs-on: ubuntu-latest
      environment: production

      steps:
        - name: "Set up Node.js"
          uses: actions/setup-node@v4
          with:
            node-version: '21'
          
        - name: "Setup versel CLI"
          run: npm install -g vercel

        - name: "Download build artifacts"
          uses: actions/download-artifact@v4
          with:
            name: build
            run-id: ${{ github.event.workflow_run.id }}
            github-token: ${{ github.token }}

        - name: "Deploy to Vercel"
          run : vercel --prod --token= $VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }} --confirm --name=cicdproduction
          
               
